site_name: Kubernetes Myths
site_description: Busting common Kubernetes misconceptions with real-world analysis and insights.
#author: Rajesh Deshpande
site_author: Rajesh Deshpande
#site_title: Kubernetes Myths; Debunking Common Misconceptions
site_url: https://kubernetesmyths.com

extra:
  homepage: https://kubernetesmyths.com
  favicon: images/favicon.png
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajeshdeshpande02/

plugins:
  - search
  - meta-descriptions

theme:
  name: material
  #logo: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css


nav:
  - Home: index.md
 
  - Architecture Myths: 
      - Overview: architecture_myths/overview.md
      - Kubelet is Exclusive to Worker Nodes: architecture_myths/Kubelet_is_Exclusive_to_Worker_Nodes.md
      - Kubernetes Clusters Can't Function Without Kube-Proxy: architecture_myths/Kubernetes_Clusters_Can't_Function_Without_Kube-Proxy.md
      - Kubernetes Networking Works Fine Without a CNI Plugin: architecture_myths/Kubernetes_Networking_Works_Fine_Without_a_CNI_Plugin.md
      - Control Plane Nodes Don’t Need a Container Runtime: architecture_myths/Control_Plane_Nodes_Don’t_Need_a_Container_Runtime.md
   
  - Workload Myths:
      - Overview: workload_myths/overview.md
      - Rolling Updates Are Only Supported by Deployments: workload_myths/Rolling_Updates_Are_Only_Supported_by_Deployments.md
      - DaemonSet always schedule pods on all nodes: workload_myths/DaemonSet_always_schedule_pods_on_all_nodes.md
      - Deployment Supports All Pod Restart Policies: workload_myths/Deployment_Supports_All_Pod_Restart_Policies.md
      - Kubernetes automatically roll back failed Deployment: workload_myths/Kubernetes_automatically_roll_back_failed_deployment.md
      - K8s always injects information about Services into a Pods: workload_myths/K8s_Injects_Svc_Info_Into_A_Pods_Env_Var.md
      

  - Networking Myths:
      - Overview: networking_myths/overview.md
      - kube-proxy assign IP address to Pods: networking_myths/kube-proxy_assign_IP_address_to_Pods.md
      - ClusterIP Service is Only for Internal Traffic: networking_myths/ClusterIP_Service_is_Only_for_Internal_Traffic.md
      - ClusterIP Service Always Use Round-Robin Load Balancing: networking_myths/ClusterIP_Services_Always_Use_Round-Robin_Load_Balancing.md
      - kubectl port-forward svc sends traffic to a service: networking_myths/kubectl_port-forward_svc_sends_traffic_to_a_service.md

  - Storage Myths:
      - Overview: storage_myths/overview.md
      - Kubernetes Cluster Can Have Only One Default StorageClass: storage_myths/Kubernetes_Cluster_Can_Have_Only_One_Default_StorageClass.md
      - ReadWriteOnce mode allows only a single Pod to access the volume: storage_myths/ReadWriteOnce_mode_allows_only_a_single_Pod_to_access_the_volume.md
  

  - Security Myths:
      - Overview: security_myths/overview.md
  - General Myths:
      - Overview: general_myths/overview.md
      - Kubernetes Namespaces Provide Complete Isolation: general_myths/Kubernetes_Namespaces_Provide_Complete_Isolation.md
      - Complete application can be rolled back in Kubernetes: general_myths/Complete_application_can_be_rolled_back_in_Kubernetes.md

  - Author: about.md
  #- About: about.md